apiVersion: v2  # Update from v1 to v2
name: nginx-deployment
description: Install Nginx deployment manifests 
type: application  # Add this line
keywords:
- nginx
version: 1.0.0
maintainers:
- name: student
  email: student@example.com