namespace:
  name: staging

service:
  port: 80
  type: ClusterIP

image:
  repository: nginx 
  tag: 1.18.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.17.0"