name space: demo

service:
  type: ClusterIP
  port: 8111

replicaCount: 3

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
resources: 
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: alpine"
